export interface Product {
  id: string;
  name: string;
  category: string;
  description: string;
  image: string;
  price: number;
  unit: string;
  specifications?: string[];
  popular?: boolean;
  inStock?: boolean;
}

export interface Category {
  id: string;
  name: string;
  image: string;
  description: string;
}

export const categories: Category[] = [
  { id: "building-materials", name: "Building Materials", image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&auto=format&fit=crop&q=60", description: "Cement, sand, ballast, bricks, stones, blocks" },
  { id: "steel", name: "Steel & Reinforcement", image: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=600&auto=format&fit=crop&q=60", description: "Steel bars, binding wire, hoop iron" },
  { id: "timber", name: "Timber & Boards", image: "https://images.unsplash.com/photo-1541123603104-512919d6a96c?w=600&auto=format&fit=crop&q=60", description: "Timber, plywood, MDF, chipboard" },
  { id: "roofing", name: "Roofing Materials", image: "https://images.unsplash.com/photo-1632759145351-1d592919f522?w=600&auto=format&fit=crop&q=60", description: "Roofing sheets, ridges, gutters, downpipes" },
  { id: "plumbing", name: "Plumbing & Water Systems", image: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&auto=format&fit=crop&q=60", description: "Tanks, pipes, pumps, taps, toilets, sinks" },
  { id: "tiles", name: "Tiles & Flooring", image: "https://images.unsplash.com/photo-1620626012053-6b3646e2931b?w=600&auto=format&fit=crop&q=60", description: "Floor tiles, wall tiles, adhesives, grouts" },
  { id: "paints", name: "Paints & Finishes", image: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=600&auto=format&fit=crop&q=60", description: "Paints, primers, thinners, brushes, rollers" },
  { id: "electrical", name: "Electrical & Lighting", image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&auto=format&fit=crop&q=60", description: "Cables, switches, sockets, lighting fixtures" },
  { id: "solar", name: "Solar Products", image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&auto=format&fit=crop&q=60", description: "Solar panels, batteries, inverters" },
  { id: "tools", name: "Tools & Equipment", image: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=600&auto=format&fit=crop&q=60", description: "Power tools, hand tools, welding machines" },
  { id: "hardware", name: "Hardware & Fasteners", image: "https://images.unsplash.com/photo-1581147036324-c17ac41dd161?w=600&auto=format&fit=crop&q=60", description: "Bolts, nuts, screws, nails, locks, hinges" },
  { id: "doors-windows", name: "Doors & Windows", image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=60", description: "Doors, windows, glass, aluminum profiles" },
  { id: "safety", name: "Safety Equipment", image: "https://images.unsplash.com/photo-1592434134753-a70baf7979d5?w=600&auto=format&fit=crop&q=60", description: "Safety boots, helmets, gloves, jackets" },
  { id: "fencing", name: "Fencing Materials", image: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=600&auto=format&fit=crop&q=60", description: "Fencing posts, barbed wire, chain-link" },
  { id: "ceiling", name: "Ceiling & Drywall", image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&fit=crop&q=60", description: "Gypsum boards, ceiling channels, insulation" },
];

export const products: Product[] = [
  // Building Materials
  { id: "cement", name: "Simba/Bamburi Cement 32.5R", category: "Building Materials", description: "High-quality Portland cement 32.5R for all construction work. 50kg bag.", image: "/products/cement.jpeg", price: 425, unit: "bag", specifications: ["50kg bag", "Grade 32.5R", "Simba/Bamburi/Savannah"], popular: true, inStock: true },
  { id: "building-stones-6x6", name: "Building Stones 6x6", category: "Building Materials", description: "Quality building stones 6x6 for foundation and wall construction.", image: "/products/building-stones-6x6.jpeg", price: 30, unit: "piece", specifications: ["6x6 inches", "Machine cut", "High strength"], inStock: true },
  { id: "sand", name: "Construction Sand", category: "Building Materials", description: "Clean river sand and coarse sand for building.", image: "/products/sand.jpeg", price: 1800, unit: "tonne", specifications: ["Clean river sand", "Washed", "Fine to coarse"], inStock: true },
  { id: "ballast-34", name: "Ballast 3/4 Inch", category: "Building Materials", description: "Crushed stone ballast for concrete mixing.", image: "https://image.pollinations.ai/prompt/product+photography+crushed+stone+gravel+ballast+three+quarter+inch+aggregate+pile+grey+construction+material+realistic?width=600&height=600&nologo=true&model=flux&seed=104", price: 2200, unit: "tonne", specifications: ["3/4 inch", "Hard stones", "Clean"], popular: true, inStock: true },
  { id: "ballast-12", name: "Ballast 1/2 Inch", category: "Building Materials", description: "Crushed stone ballast. 1/2 inch size.", image: "/products/ballast-12.jpeg", price: 2200, unit: "tonne", specifications: ["1/2 inch", "Hard stones", "Clean"], inStock: true },
  { id: "stones-machine", name: "Machine Cut Stones 6x9", category: "Building Materials", description: "Machine-cut building stones 6x9 for foundation and wall construction.", image: "/products/stones-machine.jpeg", price: 35, unit: "piece", specifications: ["6x9 inches", "Machine cut", "Uniform"], inStock: true },
  { id: "bricks", name: "Clay Bricks", category: "Building Materials", description: "High-quality fired clay bricks for wall construction.", image: "/products/bricks.jpeg", price: 15, unit: "piece", specifications: ["Fired clay", "Standard size", "Red bricks"], inStock: true },
  { id: "quarry-dust", name: "Quarry Dust", category: "Building Materials", description: "Fine quarry dust for blinding and plastering.", image: "/products/quarry-dust.jpeg", price: 1200, unit: "tonne", specifications: ["Fine dust", "Screened", "Clean"], inStock: true },
  { id: "blocks-4", name: "Concrete Blocks 4 Inch", category: "Building Materials", description: "Solid and hollow concrete blocks. 4 inch thickness.", image: "https://image.pollinations.ai/prompt/professional+product+photo+hollow+concrete+building+block+4+inch+thick+grey+white+background+studio?width=600&height=600&nologo=true&model=flux&seed=109", price: 45, unit: "piece", specifications: ["4 inch", "Hollow/solid", "High strength"], inStock: true },
  { id: "blocks-6", name: "Concrete Blocks 6 Inch", category: "Building Materials", description: "Solid and hollow concrete blocks. 6 inch thickness.", image: "https://image.pollinations.ai/prompt/professional+product+photo+hollow+concrete+building+block+6+inch+thick+grey+white+background?width=600&height=600&nologo=true&model=flux&seed=110", price: 55, unit: "piece", specifications: ["6 inch", "Hollow/solid", "High strength"], inStock: true },
  { id: "blocks-9", name: "Concrete Blocks 9 Inch", category: "Building Materials", description: "Solid and hollow concrete blocks. 9 inch thickness.", image: "https://image.pollinations.ai/prompt/professional+product+photo+solid+concrete+building+block+9+inch+thick+heavy+grey+white+background?width=600&height=600&nologo=true&model=flux&seed=111", price: 75, unit: "piece", specifications: ["9 inch", "Hollow/solid", "High strength"], inStock: true },
  { id: "cabro", name: "Cabro Paving Blocks", category: "Building Materials", description: "Interlocking concrete paving blocks for driveways.", image: "https://image.pollinations.ai/prompt/professional+photo+interlocking+concrete+paving+blocks+colorful+driveway+pavers+cabro+multiple+colors+white+background?width=600&height=600&nologo=true&model=flux&seed=112", price: 85, unit: "sqm", specifications: ["60mm thick", "Multiple colors", "Interlocking"], popular: true, inStock: true },

  // Steel & Reinforcement
  { id: "steel-d8", name: "Steel Bars D8 (8mm)", category: "Steel & Reinforcement", description: "High-tensile steel reinforcement bars. 8mm diameter.", image: "https://image.pollinations.ai/prompt/professional+product+photography+bundle+of+steel+reinforcement+rebar+bars+8mm+diameter+grey+metal+white+background+studio?width=600&height=600&nologo=true&model=flux&seed=113", price: 650, unit: "piece", specifications: ["8mm diameter", "12m length", "Grade 500B"], inStock: true },
  { id: "steel-d10", name: "Steel Bars D10 (10mm)", category: "Steel & Reinforcement", description: "High-tensile steel reinforcement bars. 10mm diameter.", image: "https://image.pollinations.ai/prompt/professional+product+photography+steel+reinforcement+rebar+10mm+diameter+bundle+grey+metal+construction+white+background?width=600&height=600&nologo=true&model=flux&seed=114", price: 950, unit: "piece", specifications: ["10mm diameter", "12m length", "Grade 500B"], inStock: true },
  { id: "steel-d12", name: "Steel Bars D12 (12mm)", category: "Steel & Reinforcement", description: "High-tensile steel reinforcement bars. 12mm diameter.", image: "https://image.pollinations.ai/prompt/professional+product+photography+high+tensile+steel+reinforcement+rebar+12mm+bundle+grey+metal+bars+white+background?width=600&height=600&nologo=true&model=flux&seed=115", price: 1350, unit: "piece", specifications: ["12mm diameter", "12m length", "Grade 500B"], popular: true, inStock: true },
  { id: "steel-d16", name: "Steel Bars D16 (16mm)", category: "Steel & Reinforcement", description: "High-tensile steel reinforcement bars. 16mm diameter.", image: "https://image.pollinations.ai/prompt/professional+product+photography+heavy+steel+reinforcement+rebar+16mm+diameter+bundle+grey+metal+white+background+studio?width=600&height=600&nologo=true&model=flux&seed=116", price: 2350, unit: "piece", specifications: ["16mm diameter", "12m length", "Grade 500B"], popular: true, inStock: true },
  { id: "binding-wire", name: "Binding Wire 16 Gauge (25kg)", category: "Steel & Reinforcement", description: "Annealed binding wire 16 gauge for tying steel reinforcement bars. 25kg roll.", image: "https://image.pollinations.ai/prompt/product+photography+galvanized+annealed+steel+binding+wire+coil+roll+16+gauge+25kg+dark+metal+white+background?width=600&height=600&nologo=true&model=flux&seed=117", price: 1925, unit: "25kg roll", specifications: ["16 Gauge", "25kg roll", "Annealed"], popular: true, inStock: true },
  { id: "brc-mesh", name: "BRC Wire Mesh", category: "Steel & Reinforcement", description: "Welded wire mesh for concrete reinforcement.", image: "https://image.pollinations.ai/prompt/professional+product+photo+welded+steel+wire+mesh+BRC+sheet+concrete+reinforcement+grid+grey+metal+white+background?width=600&height=600&nologo=true&model=flux&seed=118", price: 5500, unit: "sheet", specifications: ["A142/A193/A252", "Welded mesh", "4.8m x 2.4m"], inStock: true },

  // Timber & Boards
  { id: "timber-2x2", name: "Cypress Timber 2x2 (per foot)", category: "Timber & Boards", description: "Roofing cypress timber 2x2 inches. Priced per foot. Treated.", image: "https://image.pollinations.ai/prompt/product+photography+treated+cypress+timber+2x2+inch+lumber+planks+roofing+wood+natural+grain+white+background+studio?width=600&height=600&nologo=true&model=flux&seed=119", price: 17, unit: "foot", specifications: ["2x2 inches", "Cypress", "Roofing grade"], popular: true, inStock: true },
  { id: "timber-3x2", name: "Cypress Timber 3x2 (per foot)", category: "Timber & Boards", description: "Roofing cypress timber 3x2 inches. Priced per foot. Treated.", image: "https://image.pollinations.ai/prompt/product+photography+treated+cypress+timber+3x2+inch+lumber+planks+construction+wood+natural+grain+white+background?width=600&height=600&nologo=true&model=flux&seed=120", price: 22, unit: "foot", specifications: ["3x2 inches", "Cypress", "Roofing grade"], popular: true, inStock: true },
  { id: "timber-4x2", name: "Cypress Timber 4x2 (per foot)", category: "Timber & Boards", description: "Roofing cypress timber 4x2 inches. Priced per foot. Treated.", image: "https://image.pollinations.ai/prompt/product+photography+treated+cypress+timber+4x2+inch+roofing+lumber+planks+natural+wood+grain+white+background?width=600&height=600&nologo=true&model=flux&seed=121", price: 30, unit: "foot", specifications: ["4x2 inches", "Cypress", "Roofing grade"], inStock: true },
  { id: "timber-2x6", name: "Timber 2x6 (50x150mm)", category: "Timber & Boards", description: "Treated timber for construction. 2x6 inches.", image: "https://image.pollinations.ai/prompt/product+photography+treated+construction+timber+planks+50x150mm+2x6+inch+stacked+wood+lumber+white+background?width=600&height=600&nologo=true&model=flux&seed=122", price: 245, unit: "meter", specifications: ["50x150mm", "Treated", "Cypress/Pine"], inStock: true },
  { id: "plywood-6mm", name: "Plywood 6mm", category: "Timber & Boards", description: "Commercial plywood for furniture. 6mm thickness.", image: "https://image.pollinations.ai/prompt/professional+product+photo+commercial+plywood+sheet+6mm+thin+furniture+grade+wooden+board+white+background+studio?width=600&height=600&nologo=true&model=flux&seed=123", price: 2200, unit: "sheet", specifications: ["6mm thick", "4x8 feet", "Commercial grade"], inStock: true },
  { id: "plywood-12mm", name: "Plywood 12mm", category: "Timber & Boards", description: "Commercial/Marine plywood. 12mm thickness.", image: "https://image.pollinations.ai/prompt/professional+product+photo+marine+plywood+sheet+12mm+thick+commercial+grade+boards+white+background+studio?width=600&height=600&nologo=true&model=flux&seed=124", price: 3500, unit: "sheet", specifications: ["12mm thick", "4x8 feet", "Commercial/Marine"], popular: true, inStock: true },
  { id: "plywood-18mm", name: "Plywood 18mm", category: "Timber & Boards", description: "Marine plywood for wet areas. 18mm thickness.", image: "https://image.pollinations.ai/prompt/professional+product+photo+marine+grade+plywood+18mm+thick+heavy+duty+sheets+white+background+studio?width=600&height=600&nologo=true&model=flux&seed=125", price: 4800, unit: "sheet", specifications: ["18mm thick", "4x8 feet", "Marine grade"], inStock: true },
  { id: "mdf-6mm", name: "MDF Board 6mm", category: "Timber & Boards", description: "Medium Density Fiberboard. 6mm.", image: "https://image.pollinations.ai/prompt/professional+product+photo+MDF+medium+density+fiberboard+board+6mm+smooth+white+surface+sheet+white+background?width=600&height=600&nologo=true&model=flux&seed=126", price: 1800, unit: "sheet", specifications: ["6mm thick", "4x8 feet", "Smooth finish"], inStock: true },
  { id: "mdf-12mm", name: "MDF Board 12mm", category: "Timber & Boards", description: "Medium Density Fiberboard. 12mm.", image: "https://image.pollinations.ai/prompt/professional+product+photo+MDF+medium+density+fiberboard+12mm+smooth+finish+furniture+board+white+background?width=600&height=600&nologo=true&model=flux&seed=127", price: 3000, unit: "sheet", specifications: ["12mm thick", "4x8 feet", "Smooth finish"], popular: true, inStock: true },
  { id: "chipboard", name: "Chipboard 18mm", category: "Timber & Boards", description: "Particle board for furniture making.", image: "https://image.pollinations.ai/prompt/professional+product+photo+particle+chipboard+18mm+thick+furniture+making+board+sheet+white+background+studio?width=600&height=600&nologo=true&model=flux&seed=128", price: 2200, unit: "sheet", specifications: ["18mm thick", "4x8 feet", "Particle board"], inStock: true },

  // Roofing Materials
  { id: "corrugated-30g", name: "30 Gauge 3M Corrugated Iron Sheet", category: "Roofing Materials", description: "30 gauge corrugated iron roofing sheet. 3 meter length. Various colors.", image: "https://image.pollinations.ai/prompt/professional+product+photography+corrugated+galvanized+iron+roofing+sheet+mabati+3+meter+green+colored+stack+white+background?width=600&height=600&nologo=true&model=flux&seed=129", price: 630, unit: "sheet", specifications: ["Gauge 30", "3m length", "Multiple colors"], popular: true, inStock: true },
  { id: "corrugated-30g-2m", name: "30 Gauge 2M Corrugated Iron Sheet", category: "Roofing Materials", description: "30 gauge corrugated iron roofing sheet. 2 meter length.", image: "https://image.pollinations.ai/prompt/professional+product+photography+corrugated+iron+roofing+sheet+2+meter+galvanized+colored+mabati+white+background?width=600&height=600&nologo=true&model=flux&seed=130", price: 475, unit: "sheet", specifications: ["Gauge 30", "2m length", "Multiple colors"], inStock: true },
  { id: "corrugated-30g-25m", name: "30 Gauge 2.5M Corrugated Iron Sheet", category: "Roofing Materials", description: "30 gauge corrugated iron roofing sheet. 2.5 meter length.", image: "https://image.pollinations.ai/prompt/professional+product+photo+corrugated+iron+roofing+sheets+2.5+meter+galvanized+metal+stack+white+background?width=600&height=600&nologo=true&model=flux&seed=131", price: 555, unit: "sheet", specifications: ["Gauge 30", "2.5m length", "Multiple colors"], inStock: true },
  { id: "corrugated-32g", name: "32 Gauge 3M Corrugated Iron Sheet", category: "Roofing Materials", description: "32 gauge corrugated iron roofing sheet. 3 meter length.", image: "https://image.pollinations.ai/prompt/professional+product+photo+corrugated+iron+roofing+sheet+32+gauge+galvanized+metal+3+meter+white+background?width=600&height=600&nologo=true&model=flux&seed=132", price: 565, unit: "sheet", specifications: ["Gauge 32", "3m length", "Multiple colors"], inStock: true },
  { id: "box-profile-30g", name: "Box Profile Roofing Sheet 30G 3M", category: "Roofing Materials", description: "30 gauge box profile roofing sheet 3 meter. Modern tile look.", image: "https://image.pollinations.ai/prompt/professional+product+photography+box+profile+metal+roofing+sheet+tile+effect+modern+colored+red+green+white+background?width=600&height=600&nologo=true&model=flux&seed=133", price: 700, unit: "sheet", specifications: ["Gauge 30", "3m length", "Tile profile"], popular: true, inStock: true },
  { id: "roofing-nails", name: "Roofing Nails", category: "Roofing Materials", description: "Galvanized roofing nails with rubber washers.", image: "https://image.pollinations.ai/prompt/product+photography+galvanized+roofing+nails+rubber+washers+bag+hardware+close+up+white+background+studio?width=600&height=600&nologo=true&model=flux&seed=134", price: 450, unit: "kg", specifications: ["Galvanized", "With washers", "Various sizes"], inStock: true },
  { id: "pvc-gutters", name: "PVC Gutters", category: "Roofing Materials", description: "PVC rain gutters. 4 inch and 6 inch.", image: "https://image.pollinations.ai/prompt/professional+product+photography+PVC+rain+water+gutter+4+inch+white+plastic+drainage+roofing+white+background?width=600&height=600&nologo=true&model=flux&seed=135", price: 450, unit: "piece", specifications: ["4 inch / 6 inch", "3m length", "With fittings"], popular: true, inStock: true },
  { id: "pvc-downpipes", name: "PVC Downpipes", category: "Roofing Materials", description: "PVC downpipes for rainwater drainage.", image: "https://image.pollinations.ai/prompt/professional+product+photo+PVC+downpipe+rainwater+drainage+pipe+3+inch+white+plastic+white+background?width=600&height=600&nologo=true&model=flux&seed=136", price: 380, unit: "piece", specifications: ["3 inch / 4 inch", "3m length", "With brackets"], inStock: true },

  // Plumbing & Water Systems
  { id: "tank-100l", name: "RotoTank 100L Water Tank", category: "Plumbing & Water Systems", description: "RotoTank cylindrical water storage tank. 100 liters capacity.", image: "https://image.pollinations.ai/prompt/professional+product+photography+cylindrical+white+plastic+water+storage+tank+100+liters+small+outdoor+water+tank+white+background?width=600&height=600&nologo=true&model=flux&seed=137", price: 2200, unit: "piece", specifications: ["100 liters", "UV resistant", "RotoTank brand"], inStock: true },
  { id: "tank-500l", name: "RotoTank 500L Water Tank", category: "Plumbing & Water Systems", description: "RotoTank cylindrical water storage tank. 500 liters capacity.", image: "https://image.pollinations.ai/prompt/professional+product+photography+cylindrical+plastic+water+storage+tank+500+liters+white+blue+outdoor+white+background?width=600&height=600&nologo=true&model=flux&seed=138", price: 5500, unit: "piece", specifications: ["500 liters", "UV resistant", "RotoTank brand"], inStock: true },
  { id: "tank-1000l", name: "RotoTank 1000L Water Tank", category: "Plumbing & Water Systems", description: "RotoTank cylindrical water storage tank. 1000 liters capacity.", image: "https://image.pollinations.ai/prompt/professional+product+photography+cylindrical+white+plastic+water+tank+1000+liters+large+outdoor+water+storage+white+background?width=600&height=600&nologo=true&model=flux&seed=139", price: 10450, unit: "piece", specifications: ["1000 liters", "UV resistant", "RotoTank brand"], popular: true, inStock: true },
  { id: "tank-1350l", name: "RotoTank 1350L Water Tank", category: "Plumbing & Water Systems", description: "RotoTank cylindrical water storage tank. 1350 liters capacity.", image: "https://image.pollinations.ai/prompt/professional+product+photo+cylindrical+plastic+water+storage+tank+1350+liters+black+outdoor+water+tank+white+background?width=600&height=600&nologo=true&model=flux&seed=140", price: 13500, unit: "piece", specifications: ["1350 liters", "UV resistant", "RotoTank brand"], inStock: true },
  { id: "tank-1500l", name: "RotoTank 1500L Water Tank", category: "Plumbing & Water Systems", description: "RotoTank cylindrical water storage tank. 1500 liters capacity.", image: "https://image.pollinations.ai/prompt/professional+product+photo+cylindrical+plastic+water+storage+tank+1500+liters+outdoor+large+white+background?width=600&height=600&nologo=true&model=flux&seed=141", price: 15000, unit: "piece", specifications: ["1500 liters", "UV resistant", "RotoTank brand"], inStock: true },
  { id: "tank-2000l", name: "RotoTank 2000L Water Tank", category: "Plumbing & Water Systems", description: "RotoTank cylindrical water storage tank. 2000 liters capacity.", image: "https://image.pollinations.ai/prompt/professional+product+photo+large+cylindrical+black+plastic+water+storage+tank+2000+liters+outdoor+white+background?width=600&height=600&nologo=true&model=flux&seed=142", price: 18500, unit: "piece", specifications: ["2000 liters", "UV resistant", "RotoTank brand"], inStock: true },
  { id: "tank-2500l", name: "RotoTank 2500L Water Tank", category: "Plumbing & Water Systems", description: "RotoTank cylindrical water storage tank. 2500 liters capacity.", image: "https://image.pollinations.ai/prompt/professional+product+photo+very+large+cylindrical+plastic+water+storage+tank+2500+liters+outdoor+white+background?width=600&height=600&nologo=true&model=flux&seed=143", price: 22000, unit: "piece", specifications: ["2500 liters", "UV resistant", "RotoTank brand"], inStock: true },
  { id: "tank-5000l", name: "RotoTank 5000L Water Tank", category: "Plumbing & Water Systems", description: "RotoTank cylindrical water storage tank. 5000 liters capacity.", image: "https://image.pollinations.ai/prompt/professional+product+photo+massive+cylindrical+plastic+water+storage+tank+5000+liters+outdoor+large+white+background?width=600&height=600&nologo=true&model=flux&seed=144", price: 38000, unit: "piece", specifications: ["5000 liters", "UV resistant", "RotoTank brand"], popular: true, inStock: true },
  { id: "pvc-pipes", name: "PVC Pressure Pipes", category: "Plumbing & Water Systems", description: "PVC pressure pipes for water supply. Classes B, C, D.", image: "https://image.pollinations.ai/prompt/product+photography+PVC+pressure+pipes+blue+plumbing+water+supply+stack+white+background+studio?width=600&height=600&nologo=true&model=flux&seed=145", price: 450, unit: "meter", specifications: ["Class B/C/D", "20mm-200mm", "Pressure rated"], inStock: true },
  { id: "hdpe-pipes", name: "HDPE Pipes", category: "Plumbing & Water Systems", description: "High-density polyethylene pipes for water supply.", image: "https://image.pollinations.ai/prompt/product+photography+HDPE+black+polyethylene+water+pipe+coil+roll+plumbing+white+background+studio?width=600&height=600&nologo=true&model=flux&seed=146", price: 550, unit: "meter", specifications: ["PN6-PN16", "20mm-315mm", "PE100"], inStock: true },
  { id: "submersible-pump", name: "Submersible Pump", category: "Plumbing & Water Systems", description: "Submersible pump for boreholes and wells.", image: "https://image.pollinations.ai/prompt/professional+product+photography+submersible+water+pump+electric+stainless+steel+borehole+pump+white+background?width=600&height=600&nologo=true&model=flux&seed=147", price: 12500, unit: "piece", specifications: ["0.5-2 HP", "220V/380V", "Deep well"], popular: true, inStock: true },
  { id: "kitchen-tap", name: "Kitchen Mixer Tap", category: "Plumbing & Water Systems", description: "Modern kitchen mixer tap with swivel spout.", image: "https://image.pollinations.ai/prompt/professional+product+photography+chrome+kitchen+mixer+tap+faucet+swivel+spout+modern+white+background+studio?width=600&height=600&nologo=true&model=flux&seed=148", price: 1850, unit: "piece", specifications: ["Chrome finish", "Swivel spout", "Ceramic cartridge"], popular: true, inStock: true },
  { id: "shower-set", name: "Shower Set Complete", category: "Plumbing & Water Systems", description: "Complete shower kit with mixer, head, and accessories.", image: "https://image.pollinations.ai/prompt/professional+product+photography+complete+chrome+shower+set+mixer+valve+shower+head+handheld+bathroom+white+background?width=600&height=600&nologo=true&model=flux&seed=149", price: 3850, unit: "set", specifications: ["Mixer valve", "Shower head", "Hand shower"], popular: true, inStock: true },
  { id: "toilet-suite", name: "Toilet Suite", category: "Plumbing & Water Systems", description: "Complete toilet with cistern and soft close seat.", image: "https://image.pollinations.ai/prompt/professional+product+photography+white+ceramic+toilet+suite+close+coupled+cistern+dual+flush+soft+close+seat+white+background?width=600&height=600&nologo=true&model=flux&seed=150", price: 8500, unit: "piece", specifications: ["Close coupled", "Soft close seat", "Dual flush"], popular: true, inStock: true },
  { id: "kitchen-sink", name: "Stainless Steel Kitchen Sink", category: "Plumbing & Water Systems", description: "Quality stainless steel kitchen sink.", image: "https://image.pollinations.ai/prompt/professional+product+photography+stainless+steel+kitchen+sink+double+bowl+with+drainboard+304+grade+white+background?width=600&height=600&nologo=true&model=flux&seed=151", price: 4850, unit: "piece", specifications: ["Single/double bowl", "304 stainless", "With drainboard"], popular: true, inStock: true },

  // Tiles & Flooring
  { id: "floor-tiles-40x40", name: "Floor Tiles 40x40cm", category: "Tiles & Flooring", description: "Ceramic floor tiles. 40x40cm size.", image: "https://image.pollinations.ai/prompt/professional+product+photography+ceramic+floor+tiles+40x40cm+beige+cream+polished+box+and+tiles+white+background?width=600&height=600&nologo=true&model=flux&seed=152", price: 1050, unit: "sqm", specifications: ["40x40cm", "Ceramic", "Multiple colors"], inStock: true },
  { id: "floor-tiles-60x60", name: "Floor Tiles 60x60cm", category: "Tiles & Flooring", description: "Porcelain floor tiles. 60x60cm size.", image: "https://image.pollinations.ai/prompt/professional+product+photography+polished+porcelain+floor+tiles+60x60cm+grey+white+glossy+white+background+studio?width=600&height=600&nologo=true&model=flux&seed=153", price: 1650, unit: "sqm", specifications: ["60x60cm", "Porcelain", "Polished/Matt"], popular: true, inStock: true },
  { id: "wall-tiles", name: "Wall Tiles", category: "Tiles & Flooring", description: "Decorative wall tiles for kitchen and bathroom.", image: "https://image.pollinations.ai/prompt/professional+product+photography+glazed+ceramic+wall+tiles+kitchen+bathroom+decorative+pattern+25x40cm+white+background?width=600&height=600&nologo=true&model=flux&seed=154", price: 950, unit: "sqm", specifications: ["25x40cm", "Glazed", "Multiple designs"], inStock: true },
  { id: "tile-adhesive", name: "Tile Adhesive", category: "Tiles & Flooring", description: "Cement-based tile adhesive for floor and wall tiles.", image: "https://image.pollinations.ai/prompt/professional+product+photography+cement+based+tile+adhesive+25kg+bag+grey+construction+flooring+white+background?width=600&height=600&nologo=true&model=flux&seed=155", price: 650, unit: "bag", specifications: ["25kg bag", "High strength", "Interior/exterior"], inStock: true },

  // Paints & Finishes
  { id: "paint-emulsion", name: "Interior Emulsion Paint 4L", category: "Paints & Finishes", description: "Quality interior emulsion paint. 4 liter tin.", image: "https://image.pollinations.ai/prompt/professional+product+photography+interior+emulsion+paint+4+liter+metal+tin+white+cream+wall+paint+white+background+studio?width=600&height=600&nologo=true&model=flux&seed=156", price: 1850, unit: "tin", specifications: ["4 liters", "Matt/Silk", "Multiple colors"], popular: true, inStock: true },
  { id: "paint-exterior", name: "Exterior Weatherguard Paint 4L", category: "Paints & Finishes", description: "Weather-resistant exterior paint. 4 liter tin.", image: "https://image.pollinations.ai/prompt/professional+product+photography+exterior+weatherguard+paint+4+liter+tin+colorful+label+UV+resistant+white+background?width=600&height=600&nologo=true&model=flux&seed=157", price: 2250, unit: "tin", specifications: ["4 liters", "Weatherguard", "UV resistant"], popular: true, inStock: true },
  { id: "paint-gloss", name: "High Gloss Paint 1L", category: "Paints & Finishes", description: "Oil-based high gloss paint for wood and metal.", image: "https://image.pollinations.ai/prompt/professional+product+photography+high+gloss+paint+1+liter+tin+oil+based+shiny+metal+can+white+background?width=600&height=600&nologo=true&model=flux&seed=158", price: 1650, unit: "tin", specifications: ["1 liter", "High gloss", "Oil-based"], inStock: true },
  { id: "primer", name: "Universal Primer 4L", category: "Paints & Finishes", description: "Universal primer for interior and exterior use.", image: "https://image.pollinations.ai/prompt/professional+product+photography+universal+primer+paint+4+liter+white+tin+interior+exterior+label+white+background?width=600&height=600&nologo=true&model=flux&seed=159", price: 1450, unit: "tin", specifications: ["4 liters", "White", "Interior/exterior"], inStock: true },
  { id: "wood-preservative", name: "Wood Preservative 4L", category: "Paints & Finishes", description: "Treatment for timber protection against termites and rot.", image: "https://image.pollinations.ai/prompt/professional+product+photography+wood+preservative+treatment+4+liter+tin+brown+timber+protection+termite+white+background?width=600&height=600&nologo=true&model=flux&seed=160", price: 1250, unit: "tin", specifications: ["4 liters", "Clear/brown", "Termite protection"], inStock: true },
  { id: "varnish", name: "Wood Varnish 1L", category: "Paints & Finishes", description: "Clear varnish for wood protection and finishing.", image: "https://image.pollinations.ai/prompt/professional+product+photography+clear+wood+varnish+1+liter+tin+transparent+glossy+finish+white+background?width=600&height=600&nologo=true&model=flux&seed=161", price: 1450, unit: "tin", specifications: ["1 liter", "Clear/gloss", "Interior/exterior"], inStock: true },
  { id: "thinner", name: "Paint Thinner 1L", category: "Paints & Finishes", description: "Universal paint thinner and cleaner.", image: "https://image.pollinations.ai/prompt/professional+product+photography+paint+thinner+solvent+1+liter+tin+universal+cleaner+metal+can+white+background?width=600&height=600&nologo=true&model=flux&seed=162", price: 650, unit: "tin", specifications: ["1 liter", "Universal", "Cleaner/thinner"], inStock: true },
  { id: "spray-paint", name: "Spray Paint Aerosol", category: "Paints & Finishes", description: "Aerosol spray paint in various colors.", image: "https://image.pollinations.ai/prompt/professional+product+photography+aerosol+spray+paint+can+400ml+colorful+quick+dry+glossy+white+background?width=600&height=600&nologo=true&model=flux&seed=163", price: 550, unit: "can", specifications: ["400ml", "Multiple colors", "Quick dry"], inStock: true },

  // Electrical & Lighting
  { id: "cable-15mm", name: "Twin & Earth Cable 1.5mm", category: "Electrical & Lighting", description: "Electrical cable for lighting circuits. 100m roll.", image: "https://image.pollinations.ai/prompt/professional+product+photography+twin+earth+electrical+copper+cable+1.5mm+100m+drum+roll+grey+white+background?width=600&height=600&nologo=true&model=flux&seed=164", price: 1850, unit: "100m", specifications: ["1.5mm2", "Twin & earth", "Copper"], inStock: true },
  { id: "cable-25mm", name: "Twin & Earth Cable 2.5mm", category: "Electrical & Lighting", description: "Electrical cable for socket circuits. 100m roll.", image: "https://image.pollinations.ai/prompt/professional+product+photography+twin+earth+copper+electrical+cable+2.5mm+100m+drum+roll+grey+yellow+white+background?width=600&height=600&nologo=true&model=flux&seed=165", price: 2850, unit: "100m", specifications: ["2.5mm2", "Twin & earth", "Copper"], popular: true, inStock: true },
  { id: "cable-4mm", name: "Twin & Earth Cable 4mm", category: "Electrical & Lighting", description: "Electrical cable for heavy duty circuits. 100m roll.", image: "https://image.pollinations.ai/prompt/professional+product+photography+heavy+duty+twin+earth+copper+cable+4mm+100m+drum+roll+white+background+studio?width=600&height=600&nologo=true&model=flux&seed=166", price: 4250, unit: "100m", specifications: ["4mm2", "Twin & earth", "Copper"], inStock: true },
  { id: "conduit-pvc", name: "PVC Conduit 20mm", category: "Electrical & Lighting", description: "PVC conduit for electrical wiring.", image: "https://image.pollinations.ai/prompt/professional+product+photography+white+PVC+electrical+conduit+pipe+20mm+3+meter+length+white+background?width=600&height=600&nologo=true&model=flux&seed=167", price: 185, unit: "piece", specifications: ["20mm/25mm", "3m length", "With accessories"], inStock: true },
  { id: "trunking", name: "PVC Trunking", category: "Electrical & Lighting", description: "PVC cable trunking for surface wiring.", image: "https://image.pollinations.ai/prompt/professional+product+photography+white+PVC+cable+trunking+surface+wiring+conduit+with+lid+white+background?width=600&height=600&nologo=true&model=flux&seed=168", price: 285, unit: "piece", specifications: ["16x16mm to 50x50mm", "With lid", "Adhesive backing"], inStock: true },
  { id: "socket-double", name: "Double Socket Outlet", category: "Electrical & Lighting", description: "Double power socket outlet.", image: "https://image.pollinations.ai/prompt/professional+product+photography+double+13A+electrical+power+socket+outlet+white+plastic+wall+mount+white+background?width=600&height=600&nologo=true&model=flux&seed=169", price: 385, unit: "piece", specifications: ["13A", "White/metal", "USB option"], popular: true, inStock: true },
  { id: "breaker-32a", name: "MCB 32A", category: "Electrical & Lighting", description: "Miniature circuit breaker. 32 ampere.", image: "https://image.pollinations.ai/prompt/professional+product+photography+miniature+circuit+breaker+MCB+32A+white+plastic+electrical+panel+DIN+rail+white+background?width=600&height=600&nologo=true&model=flux&seed=170", price: 485, unit: "piece", specifications: ["32A", "Type B/C", "Single pole"], inStock: true },
  { id: "db-8way", name: "Distribution Board 8 Way", category: "Electrical & Lighting", description: "Consumer unit with 8 ways.", image: "https://image.pollinations.ai/prompt/professional+product+photography+electrical+distribution+board+consumer+unit+8+way+metal+enclosure+with+MCBs+white+background?width=600&height=600&nologo=true&model=flux&seed=171", price: 2850, unit: "piece", specifications: ["8 way", "Metal enclosure", "With busbar"], inStock: true },
  { id: "led-bulb-12w", name: "LED Bulb 12W", category: "Electrical & Lighting", description: "Energy-efficient LED bulb. 12 watts.", image: "https://image.pollinations.ai/prompt/professional+product+photography+LED+light+bulb+12W+E27+screw+cap+warm+white+energy+saving+white+background?width=600&height=600&nologo=true&model=flux&seed=172", price: 385, unit: "piece", specifications: ["12W", "E27/B22", "Warm/cool white"], popular: true, inStock: true },
  { id: "led-downlight", name: "LED Downlight", category: "Electrical & Lighting", description: "Recessed LED downlight for ceilings.", image: "https://image.pollinations.ai/prompt/professional+product+photography+LED+recessed+ceiling+downlight+round+slim+warm+white+light+white+background?width=600&height=600&nologo=true&model=flux&seed=173", price: 485, unit: "piece", specifications: ["6W/9W/12W", "Recessed", "Warm/cool white"], popular: true, inStock: true },
  { id: "floodlight-50w", name: "LED Floodlight 50W", category: "Electrical & Lighting", description: "Outdoor LED floodlight. 50 watts.", image: "https://image.pollinations.ai/prompt/professional+product+photography+LED+outdoor+floodlight+50W+IP65+grey+security+light+fixture+white+background?width=600&height=600&nologo=true&model=flux&seed=174", price: 1850, unit: "piece", specifications: ["50W", "IP65", "Daylight"], inStock: true },
  { id: "security-light", name: "Security Light with Sensor", category: "Electrical & Lighting", description: "Motion sensor security light.", image: "https://image.pollinations.ai/prompt/professional+product+photography+PIR+motion+sensor+LED+security+light+outdoor+wall+mount+white+background?width=600&height=600&nologo=true&model=flux&seed=175", price: 2250, unit: "piece", specifications: ["PIR sensor", "LED", "Adjustable"], popular: true, inStock: true },

  // Solar Products
  { id: "solar-panel-350w", name: "AT 350W Mono Solar Panel", category: "Solar Products", description: "AT brand 350W monocrystalline solar panel for home and commercial use.", image: "https://image.pollinations.ai/prompt/professional+product+photography+350W+monocrystalline+solar+panel+black+frame+photovoltaic+cells+white+background+studio?width=600&height=600&nologo=true&model=flux&seed=176", price: 6500, unit: "piece", specifications: ["350W", "Mono Crystalline", "AT Brand"], popular: true, inStock: true },
  { id: "solar-panel-450w", name: "AT 450W Mono Solar Panel", category: "Solar Products", description: "AT brand 450W monocrystalline solar panel for high power systems.", image: "https://image.pollinations.ai/prompt/professional+product+photography+450W+monocrystalline+solar+panel+black+aluminum+frame+photovoltaic+white+background?width=600&height=600&nologo=true&model=flux&seed=177", price: 8000, unit: "piece", specifications: ["450W", "Mono Crystalline", "AT Brand"], popular: true, inStock: true },
  { id: "solar-panel-550w", name: "AT 550W Mono Solar Panel", category: "Solar Products", description: "AT brand 550W monocrystalline solar panel for large installations.", image: "https://image.pollinations.ai/prompt/professional+product+photography+550W+large+monocrystalline+solar+panel+black+frame+commercial+photovoltaic+white+background?width=600&height=600&nologo=true&model=flux&seed=178", price: 9500, unit: "piece", specifications: ["550W", "Mono Crystalline", "AT Brand"], inStock: true },
  { id: "solar-panel-200w", name: "Solar Panel 200W", category: "Solar Products", description: "Monocrystalline solar panel. 200 watts.", image: "https://image.pollinations.ai/prompt/professional+product+photography+200W+monocrystalline+solar+panel+black+frame+photovoltaic+cells+white+background?width=600&height=600&nologo=true&model=flux&seed=179", price: 11500, unit: "piece", specifications: ["200W", "Mono", "24V"], popular: true, inStock: true },
  { id: "solar-panel-300w", name: "Solar Panel 300W", category: "Solar Products", description: "Monocrystalline solar panel. 300 watts.", image: "https://image.pollinations.ai/prompt/professional+product+photography+300W+monocrystalline+solar+panel+black+frame+photovoltaic+white+background+studio?width=600&height=600&nologo=true&model=flux&seed=180", price: 16500, unit: "piece", specifications: ["300W", "Mono", "24V"], popular: true, inStock: true },
  { id: "battery-100ah", name: "Solar Battery 100Ah", category: "Solar Products", description: "Deep cycle battery for solar systems. 100Ah.", image: "https://image.pollinations.ai/prompt/professional+product+photography+deep+cycle+lead+acid+solar+battery+100Ah+12V+black+yellow+terminals+white+background?width=600&height=600&nologo=true&model=flux&seed=181", price: 18500, unit: "piece", specifications: ["100Ah", "12V", "Deep cycle"], popular: true, inStock: true },
  { id: "battery-200ah", name: "Solar Battery 200Ah", category: "Solar Products", description: "Deep cycle battery for solar systems. 200Ah.", image: "https://image.pollinations.ai/prompt/professional+product+photography+large+deep+cycle+solar+battery+200Ah+12V+black+case+yellow+terminals+white+background?width=600&height=600&nologo=true&model=flux&seed=182", price: 34500, unit: "piece", specifications: ["200Ah", "12V", "Deep cycle"], popular: true, inStock: true },
  { id: "inverter-1kva", name: "Solar Inverter 1kVA", category: "Solar Products", description: "Pure sine wave inverter. 1kVA.", image: "https://image.pollinations.ai/prompt/professional+product+photography+solar+pure+sine+wave+inverter+1kVA+12V+black+box+LCD+display+white+background?width=600&height=600&nologo=true&model=flux&seed=183", price: 18500, unit: "piece", specifications: ["1kVA", "12V", "Pure sine wave"], inStock: true },
  { id: "inverter-2kva", name: "Solar Inverter 2kVA", category: "Solar Products", description: "Pure sine wave inverter. 2kVA.", image: "https://image.pollinations.ai/prompt/professional+product+photography+solar+inverter+2kVA+24V+pure+sine+wave+black+metal+box+LCD+white+background?width=600&height=600&nologo=true&model=flux&seed=184", price: 28500, unit: "piece", specifications: ["2kVA", "24V", "Pure sine wave"], popular: true, inStock: true },
  { id: "inverter-3kva", name: "Solar Inverter 3kVA", category: "Solar Products", description: "Pure sine wave inverter. 3kVA.", image: "https://image.pollinations.ai/prompt/professional+product+photography+solar+inverter+3kVA+24V+pure+sine+wave+inverter+charger+black+metal+white+background?width=600&height=600&nologo=true&model=flux&seed=185", price: 38500, unit: "piece", specifications: ["3kVA", "24V", "Pure sine wave"], popular: true, inStock: true },
  { id: "inverter-5kva", name: "Solar Inverter 5kVA", category: "Solar Products", description: "Pure sine wave inverter. 5kVA.", image: "https://image.pollinations.ai/prompt/professional+product+photography+large+solar+inverter+5kVA+48V+pure+sine+wave+inverter+charger+heavy+duty+white+background?width=600&height=600&nologo=true&model=flux&seed=186", price: 58500, unit: "piece", specifications: ["5kVA", "48V", "Pure sine wave"], inStock: true },
  { id: "charge-controller-30a", name: "MPPT Charge Controller 30A", category: "Solar Products", description: "MPPT solar charge controller. 30 ampere.", image: "https://image.pollinations.ai/prompt/professional+product+photography+MPPT+solar+charge+controller+30A+LCD+digital+display+black+device+white+background?width=600&height=600&nologo=true&model=flux&seed=187", price: 8500, unit: "piece", specifications: ["30A", "MPPT", "12/24V"], popular: true, inStock: true },
  { id: "solar-kit-3kw", name: "Solar Home Kit 3kW", category: "Solar Products", description: "Complete solar home system. 3kW capacity.", image: "https://image.pollinations.ai/prompt/professional+product+photography+complete+solar+home+kit+3kW+solar+panels+batteries+inverter+charge+controller+white+background?width=600&height=600&nologo=true&model=flux&seed=188", price: 125000, unit: "kit", specifications: ["3kW", "4x300W panels", "With batteries"], popular: true, inStock: true },

  // Tools & Equipment
  { id: "drill-cordless", name: "Cordless Drill Driver 18V", category: "Tools & Equipment", description: "18V cordless drill driver with batteries.", image: "https://image.pollinations.ai/prompt/professional+product+photography+18V+cordless+drill+driver+yellow+black+with+two+batteries+and+carry+case+white+background?width=600&height=600&nologo=true&model=flux&seed=189", price: 8500, unit: "piece", specifications: ["18V", "2 batteries", "With case"], popular: true, inStock: true },
  { id: "angle-grinder", name: "Angle Grinder 4.5 inch", category: "Tools & Equipment", description: "Angle grinder for cutting and grinding.", image: "https://image.pollinations.ai/prompt/professional+product+photography+4.5+inch+angle+grinder+850W+orange+black+power+tool+grinding+disc+white+background?width=600&height=600&nologo=true&model=flux&seed=190", price: 6500, unit: "piece", specifications: ["850W", "115mm", "With disc"], popular: true, inStock: true },
  { id: "circular-saw", name: "Circular Saw 185mm", category: "Tools & Equipment", description: "Circular saw for wood cutting.", image: "https://image.pollinations.ai/prompt/professional+product+photography+circular+saw+185mm+1200W+electric+power+tool+blue+black+with+blade+white+background?width=600&height=600&nologo=true&model=flux&seed=191", price: 9500, unit: "piece", specifications: ["1200W", "185mm", "With blade"], inStock: true },
  { id: "welding-machine-arc", name: "ARC Welding Machine 200A", category: "Tools & Equipment", description: "ARC welding machine for metal work.", image: "https://image.pollinations.ai/prompt/professional+product+photography+ARC+inverter+welding+machine+200A+yellow+black+with+cables+electrode+holder+white+background?width=600&height=600&nologo=true&model=flux&seed=192", price: 12500, unit: "piece", specifications: ["200A", "Inverter", "With accessories"], popular: true, inStock: true },
  { id: "generator-3kva", name: "Petrol Generator 3kVA", category: "Tools & Equipment", description: "Portable petrol generator for power backup.", image: "https://image.pollinations.ai/prompt/professional+product+photography+portable+petrol+generator+3kVA+orange+black+with+outlets+manual+start+white+background?width=600&height=600&nologo=true&model=flux&seed=193", price: 28500, unit: "piece", specifications: ["3kVA", "6.5HP", "Manual start"], popular: true, inStock: true },
  { id: "concrete-mixer", name: "Concrete Mixer 260L", category: "Tools & Equipment", description: "Portable concrete mixer for construction.", image: "https://image.pollinations.ai/prompt/professional+product+photography+portable+electric+concrete+mixer+260L+tilting+drum+orange+construction+machine+white+background?width=600&height=600&nologo=true&model=flux&seed=194", price: 48500, unit: "piece", specifications: ["260L", "Electric/Diesel", "Tilting drum"], popular: true, inStock: true },
  { id: "wheelbarrow", name: "Heavy Duty Wheelbarrow", category: "Tools & Equipment", description: "Heavy-duty construction wheelbarrow.", image: "https://image.pollinations.ai/prompt/professional+product+photography+heavy+duty+steel+wheelbarrow+85+liter+orange+pneumatic+wheel+construction+white+background?width=600&height=600&nologo=true&model=flux&seed=195", price: 3850, unit: "piece", specifications: ["85L capacity", "Pneumatic wheel", "Steel tray"], popular: true, inStock: true },
  { id: "ladder-extension", name: "Extension Ladder 3.6m", category: "Tools & Equipment", description: "Aluminum extension ladder.", image: "https://image.pollinations.ai/prompt/professional+product+photography+aluminum+extension+ladder+3.6+meter+two+section+silver+light+weight+150kg+white+background?width=600&height=600&nologo=true&model=flux&seed=196", price: 8500, unit: "piece", specifications: ["3.6m extended", "2 section", "150kg capacity"], popular: true, inStock: true },

  // Hardware & Fasteners
  { id: "bolts-m12", name: "Hex Bolts M12", category: "Hardware & Fasteners", description: "Hexagonal bolts with nuts. M12 size.", image: "https://image.pollinations.ai/prompt/professional+product+photography+M12+hexagonal+bolts+zinc+plated+with+nuts+and+washers+hardware+close+up+white+background?width=600&height=600&nologo=true&model=flux&seed=197", price: 55, unit: "piece", specifications: ["M12", "With nut", "Zinc plated"], inStock: true },
  { id: "screws-wood", name: "Wood Screws Assorted", category: "Hardware & Fasteners", description: "Assorted wood screws in various sizes.", image: "https://image.pollinations.ai/prompt/professional+product+photography+assorted+wood+screws+yellow+zinc+plated+200+pieces+plastic+box+hardware+white+background?width=600&height=600&nologo=true&model=flux&seed=198", price: 285, unit: "box", specifications: ["Assorted", "Yellow zinc", "200 pieces"], inStock: true },
  { id: "nails-common", name: "Common Nails", category: "Hardware & Fasteners", description: "Common wire nails for construction.", image: "https://image.pollinations.ai/prompt/professional+product+photography+common+wire+nails+bright+steel+2+to+6+inch+pile+construction+hardware+white+background?width=600&height=600&nologo=true&model=flux&seed=199", price: 285, unit: "kg", specifications: ["2-6 inch", "Bright steel", "General purpose"], inStock: true },
  { id: "hinges-butt", name: "Butt Hinges 4 inch", category: "Hardware & Fasteners", description: "Standard butt hinges for doors.", image: "https://image.pollinations.ai/prompt/professional+product+photography+4+inch+butt+door+hinges+zinc+plated+steel+pair+hardware+white+background?width=600&height=600&nologo=true&model=flux&seed=200", price: 185, unit: "pair", specifications: ["4 inch", "Steel", "Zinc plated"], inStock: true },
  { id: "door-lock-cylindrical", name: "Cylindrical Lock", category: "Hardware & Fasteners", description: "Cylindrical lock with knob.", image: "https://image.pollinations.ai/prompt/professional+product+photography+cylindrical+door+lock+set+satin+nickel+knob+handle+with+keys+white+background?width=600&height=600&nologo=true&model=flux&seed=201", price: 1850, unit: "piece", specifications: ["Entrance set", "With knob", "With keys"], popular: true, inStock: true },
  { id: "padlock-50mm", name: "Padlock 50mm", category: "Hardware & Fasteners", description: "Heavy-duty padlock with keys.", image: "https://image.pollinations.ai/prompt/professional+product+photography+50mm+hardened+steel+padlock+with+3+keys+security+lock+white+background?width=600&height=600&nologo=true&model=flux&seed=202", price: 850, unit: "piece", specifications: ["50mm", "Hardened steel", "3 keys"], inStock: true },

  // Doors & Windows
  { id: "door-wooden", name: "Wooden Flush Door", category: "Doors & Windows", description: "Wooden flush door. Standard size.", image: "https://image.pollinations.ai/prompt/professional+product+photography+interior+wooden+flush+door+solid+core+primed+white+standard+size+white+background?width=600&height=600&nologo=true&model=flux&seed=203", price: 5850, unit: "piece", specifications: ["2030x813x40mm", "Solid core", "Primed"], inStock: true },
  { id: "door-panel", name: "Panel Wooden Door 4 Panel", category: "Doors & Windows", description: "Panel style wooden door. Mahogany finish.", image: "https://image.pollinations.ai/prompt/professional+product+photography+4+panel+solid+wood+door+mahogany+finish+interior+door+white+background?width=600&height=600&nologo=true&model=flux&seed=204", price: 8500, unit: "piece", specifications: ["2030x813x40mm", "4 panel", "Mahogany"], popular: true, inStock: true },
  { id: "door-steel", name: "Steel Security Door", category: "Doors & Windows", description: "Steel security door with frame and lock.", image: "https://image.pollinations.ai/prompt/professional+product+photography+steel+security+door+black+metal+with+frame+and+lock+panel+design+white+background?width=600&height=600&nologo=true&model=flux&seed=205", price: 12500, unit: "piece", specifications: ["2050x900mm", "With frame", "Lock included"], popular: true, inStock: true },
  { id: "window-aluminum", name: "Aluminum Sliding Window", category: "Doors & Windows", description: "Aluminum sliding window with glass.", image: "https://image.pollinations.ai/prompt/professional+product+photography+aluminum+sliding+window+white+frame+with+clear+glass+modern+design+white+background?width=600&height=600&nologo=true&model=flux&seed=206", price: 8500, unit: "sqm", specifications: ["Sliding type", "With glass", "White/brown"], inStock: true },
  { id: "glass-clear", name: "Clear Glass 4mm", category: "Doors & Windows", description: "Clear glass for windows. Cut to size.", image: "https://image.pollinations.ai/prompt/professional+product+photography+clear+float+glass+panel+4mm+thick+transparent+window+glass+white+background?width=600&height=600&nologo=true&model=flux&seed=207", price: 1850, unit: "sqm", specifications: ["4mm thick", "Clear", "Cut to size"], inStock: true },

  // Safety Equipment
  { id: "safety-boots", name: "Safety Boots Steel Toe", category: "Safety Equipment", description: "Steel toe safety boots. Sizes 40-45.", image: "https://image.pollinations.ai/prompt/professional+product+photography+steel+toe+safety+work+boots+black+leather+oil+resistant+construction+pair+white+background?width=600&height=600&nologo=true&model=flux&seed=208", price: 2850, unit: "pair", specifications: ["Steel toe", "Oil resistant", "Sizes 40-45"], popular: true, inStock: true },
  { id: "safety-helmet", name: "Safety Helmet", category: "Safety Equipment", description: "Hard hat for construction. Adjustable.", image: "https://image.pollinations.ai/prompt/professional+product+photography+yellow+HDPE+construction+hard+hat+safety+helmet+adjustable+ratchet+white+background?width=600&height=600&nologo=true&model=flux&seed=209", price: 950, unit: "piece", specifications: ["HDPE", "Adjustable", "White/yellow"], inStock: true },
  { id: "safety-gloves", name: "Work Gloves", category: "Safety Equipment", description: "Leather work gloves. Reinforced.", image: "https://image.pollinations.ai/prompt/professional+product+photography+leather+work+gloves+reinforced+palm+construction+safety+pair+white+background?width=600&height=600&nologo=true&model=flux&seed=210", price: 450, unit: "pair", specifications: ["Leather", "Reinforced", "Universal size"], inStock: true },
  { id: "safety-vest", name: "Reflective Safety Vest", category: "Safety Equipment", description: "High visibility safety vest.", image: "https://image.pollinations.ai/prompt/professional+product+photography+high+visibility+reflective+safety+vest+orange+with+silver+strips+construction+white+background?width=600&height=600&nologo=true&model=flux&seed=211", price: 650, unit: "piece", specifications: ["Reflective", "Orange/yellow", "Universal size"], inStock: true },

  // Fencing Materials
  { id: "fence-post-concrete", name: "Concrete Fence Post", category: "Fencing Materials", description: "Concrete fence post. 2.4 meters.", image: "https://image.pollinations.ai/prompt/professional+product+photography+reinforced+concrete+fence+post+2.4+meter+grey+square+section+white+background?width=600&height=600&nologo=true&model=flux&seed=212", price: 1850, unit: "piece", specifications: ["2.4m length", "100x100mm", "Reinforced"], inStock: true },
  { id: "barbed-wire-ngombe-480m", name: "Ng'ombe Barbed Wire 480M", category: "Fencing Materials", description: "Ng'ombe brand galvanized barbed wire 480 meter roll for fencing.", image: "https://image.pollinations.ai/prompt/professional+product+photography+galvanized+steel+barbed+wire+coil+roll+480+meter+fencing+sharp+barbs+white+background?width=600&height=600&nologo=true&model=flux&seed=213", price: 3925, unit: "roll", specifications: ["480m roll", "Galvanized", "Ng'ombe brand"], popular: true, inStock: true },
  { id: "barbed-wire-ngombe-610m", name: "Ng'ombe Barbed Wire 610M", category: "Fencing Materials", description: "Ng'ombe brand galvanized barbed wire 610 meter roll.", image: "https://image.pollinations.ai/prompt/professional+product+photography+galvanized+steel+barbed+wire+large+coil+roll+610+meter+fencing+white+background?width=600&height=600&nologo=true&model=flux&seed=214", price: 4850, unit: "roll", specifications: ["610m roll", "Galvanized", "Ng'ombe brand"], inStock: true },
  { id: "barbed-wire-125g-180m", name: "Barbed Wire 12.5 Gauge 180M", category: "Fencing Materials", description: "High tensile barbed wire 12.5 gauge 180 meter roll.", image: "https://image.pollinations.ai/prompt/professional+product+photography+high+tensile+galvanized+barbed+wire+12.5+gauge+180+meter+coil+roll+fencing+white+background?width=600&height=600&nologo=true&model=flux&seed=215", price: 2750, unit: "roll", specifications: ["180m roll", "12.5 gauge", "High tensile"], inStock: true },
  { id: "barbed-wire-125g-220m", name: "Barbed Wire 12.5 Gauge 220M", category: "Fencing Materials", description: "High tensile barbed wire 12.5 gauge 220 meter roll.", image: "https://image.pollinations.ai/prompt/professional+product+photography+high+tensile+galvanized+barbed+wire+12.5+gauge+220+meter+coil+fencing+white+background?width=600&height=600&nologo=true&model=flux&seed=216", price: 3250, unit: "roll", specifications: ["220m roll", "12.5 gauge", "High tensile"], inStock: true },
  { id: "chain-link", name: "Chain Link Fence 1.8m", category: "Fencing Materials", description: "Galvanized chain link fencing mesh. 25m roll.", image: "https://image.pollinations.ai/prompt/professional+product+photography+galvanized+chain+link+fence+mesh+1.8+meter+height+25+meter+roll+diamond+pattern+white+background?width=600&height=600&nologo=true&model=flux&seed=217", price: 2850, unit: "roll", specifications: ["25m roll", "1.8m height", "Galvanized"], inStock: true },
  { id: "shade-net-90-50x3", name: "Shade Net 90% (50x3m)", category: "Fencing Materials", description: "Dark green shade net 90% visibility. 50x3 meters for greenhouse and shading.", image: "https://image.pollinations.ai/prompt/professional+product+photography+dark+green+shade+net+90+percent+greenhouse+agricultural+netting+roll+50x3+meter+white+background?width=600&height=600&nologo=true&model=flux&seed=218", price: 21000, unit: "roll", specifications: ["50x3 meters", "90% shading", "Dark green"], popular: true, inStock: true },
  { id: "shade-net-70-50x3", name: "Shade Net 70% (50x3m)", category: "Fencing Materials", description: "Dark green shade net 70% visibility. 50x3 meters.", image: "https://image.pollinations.ai/prompt/professional+product+photography+dark+green+shade+net+70+percent+agricultural+greenhouse+netting+roll+white+background?width=600&height=600&nologo=true&model=flux&seed=219", price: 15000, unit: "roll", specifications: ["50x3 meters", "70% shading", "Dark green"], inStock: true },
  { id: "shade-net-55-50x3", name: "Shade Net 55% (50x3m)", category: "Fencing Materials", description: "Dark green shade net 55% visibility. 50x3 meters.", image: "https://image.pollinations.ai/prompt/professional+product+photography+dark+green+shade+net+55+percent+agricultural+netting+roll+white+background?width=600&height=600&nologo=true&model=flux&seed=220", price: 9750, unit: "roll", specifications: ["50x3 meters", "55% shading", "Dark green"], inStock: true },
  { id: "u-nails-1kg", name: "U Nails 1kg", category: "Fencing Materials", description: "U nails for fixing fence wire to timber posts. 1kg pack.", image: "https://image.pollinations.ai/prompt/professional+product+photography+U+shaped+galvanized+fencing+wire+staple+nails+1kg+pack+hardware+close+up+white+background?width=600&height=600&nologo=true&model=flux&seed=221", price: 250, unit: "kg", specifications: ["1kg pack", "Galvanized", "Wire fencing"], inStock: true },
  { id: "u-nails-25kg", name: "U Nails 25kg", category: "Fencing Materials", description: "U nails for fixing fence wire to timber posts. 25kg pack.", image: "https://image.pollinations.ai/prompt/professional+product+photography+U+shaped+galvanized+fencing+staple+nails+25kg+bag+bulk+hardware+white+background?width=600&height=600&nologo=true&model=flux&seed=222", price: 4500, unit: "25kg", specifications: ["25kg pack", "Galvanized", "Wire fencing"], inStock: true },
  { id: "razor-wire", name: "Razor Wire (Concertina)", category: "Fencing Materials", description: "Concertina razor wire for perimeter security fencing.", image: "https://image.pollinations.ai/prompt/professional+product+photography+concertina+razor+wire+coil+galvanized+steel+security+perimeter+fencing+white+background?width=600&height=600&nologo=true&model=flux&seed=223", price: 3500, unit: "roll", specifications: ["10m roll", "High tensile", "Security grade"], popular: true, inStock: true },
  { id: "gabion-basket", name: "Gabion Basket", category: "Fencing Materials", description: "Galvanized gabion basket for retaining walls and landscaping.", image: "https://image.pollinations.ai/prompt/professional+product+photography+galvanized+gabion+basket+wire+mesh+box+1x1x1+meter+retaining+wall+landscape+white+background?width=600&height=600&nologo=true&model=flux&seed=224", price: 2850, unit: "piece", specifications: ["1x1x1m", "Galvanized mesh", "Heavy gauge"], inStock: true },
  { id: "high-tensile-wire", name: "High Tensile Wire", category: "Fencing Materials", description: "High tensile galvanized fencing wire for farm and perimeter fencing.", image: "https://image.pollinations.ai/prompt/professional+product+photography+high+tensile+galvanized+fencing+wire+500+meter+coil+roll+farm+perimeter+white+background?width=600&height=600&nologo=true&model=flux&seed=225", price: 3200, unit: "roll", specifications: ["500m roll", "High tensile", "Galvanized"], inStock: true },
  { id: "chicken-wire", name: "Chicken Wire (Hexagonal)", category: "Fencing Materials", description: "Galvanized hexagonal chicken wire mesh for poultry and garden fencing.", image: "https://image.pollinations.ai/prompt/professional+product+photography+galvanized+hexagonal+chicken+wire+mesh+poultry+netting+30+meter+roll+white+background?width=600&height=600&nologo=true&model=flux&seed=226", price: 2200, unit: "roll", specifications: ["30m roll", "1m height", "Galvanized"], inStock: true },
  { id: "clear-view-fence", name: "Clear View Fence Panel", category: "Fencing Materials", description: "Clear view welded mesh fencing panel for security.", image: "https://image.pollinations.ai/prompt/professional+product+photography+clear+view+welded+mesh+security+fence+panel+powder+coated+green+2.4x2+meter+white+background?width=600&height=600&nologo=true&model=flux&seed=227", price: 3500, unit: "panel", specifications: ["2.4x2m", "3x4mm wire", "Powder coated"], inStock: true },

  // Ceiling & Drywall
  { id: "gypsum-board", name: "Gypsum Board 9mm", category: "Ceiling & Drywall", description: "Standard gypsum board for ceilings and walls.", image: "https://image.pollinations.ai/prompt/professional+product+photography+gypsum+plasterboard+9mm+standard+drywall+sheet+2400x1200mm+white+smooth+white+background?width=600&height=600&nologo=true&model=flux&seed=228", price: 1250, unit: "sheet", specifications: ["2400x1200x9mm", "Standard", "Square edge"], popular: true, inStock: true },
  { id: "gypsum-moisture", name: "Moisture Resistant Gypsum", category: "Ceiling & Drywall", description: "Moisture resistant gypsum board. Green board.", image: "https://image.pollinations.ai/prompt/professional+product+photography+moisture+resistant+green+gypsum+board+drywall+12mm+bathroom+kitchen+sheet+white+background?width=600&height=600&nologo=true&model=flux&seed=229", price: 1650, unit: "sheet", specifications: ["2400x1200x12mm", "Green board", "Bathroom use"], inStock: true },
  { id: "ceiling-tile", name: "PVC Ceiling Tile", category: "Ceiling & Drywall", description: "PVC ceiling tiles. 600x600mm. Various patterns.", image: "https://image.pollinations.ai/prompt/professional+product+photography+PVC+ceiling+tile+600x600mm+decorative+embossed+pattern+white+glossy+white+background?width=600&height=600&nologo=true&model=flux&seed=230", price: 850, unit: "piece", specifications: ["600x600mm", "Multiple patterns", "White"], inStock: true },
  { id: "insulation-fiber", name: "Fiber Glass Insulation", category: "Ceiling & Drywall", description: "Fiber glass wool insulation. 10m2 coverage.", image: "https://image.pollinations.ai/prompt/professional+product+photography+fiberglass+wool+insulation+roll+50mm+yellow+thermal+acoustic+ceiling+white+background?width=600&height=600&nologo=true&model=flux&seed=231", price: 2850, unit: "roll", specifications: ["50mm thick", "10m2 coverage", "Thermal/acoustic"], inStock: true },
];

export const testimonials = [
  {
    id: 1,
    name: "John Kamau",
    role: "Building Contractor",
    content: "Foundation Hardware has been our go-to supplier for all construction materials. Their prices are competitive and delivery is always on time. The WhatsApp ordering makes it so convenient!",
    rating: 5,
  },
  {
    id: 2,
    name: "Sarah Wanjiku",
    role: "Home Owner",
    content: "I was renovating my house and Foundation Hardware had everything I needed. From tiles to paint to electrical supplies. Great quality products and excellent customer service.",
    rating: 5,
  },
  {
    id: 3,
    name: "Michael Ochieng",
    role: "Plumber",
    content: "As a professional plumber, I need reliable suppliers. Foundation Hardware stocks quality plumbing materials at fair prices. Their PVC pipes and fittings are top grade.",
    rating: 5,
  },
  {
    id: 4,
    name: "Grace Muthoni",
    role: "Interior Designer",
    content: "I recommend Foundation Hardware to all my clients. They have a wide selection of premium tiles, paints, and finishes. The product quality is consistently excellent.",
    rating: 5,
  },
];

export const WHY_CHOOSE_US = [
  {
    title: "Quality Products",
    description: "We source only the best building materials from trusted manufacturers.",
  },
  {
    title: "Competitive Prices",
    description: "Get the best value for your money with our fair and transparent pricing.",
  },
  {
    title: "Fast Delivery",
    description: "We deliver to your site quickly, saving you time and hassle.",
  },
  {
    title: "Expert Advice",
    description: "Our knowledgeable staff can help you choose the right materials for your project.",
  },
];

export const getProductById = (id: string) => {
  return products.find((product) => product.id === id);
};

export const getProductsByCategory = (category: string) => {
  return products.filter((product) => product.category === category);
};

export const getRelatedProducts = (product: Product, limit = 4) => {
  return products
    .filter((p) => p.category === product.category && p.id !== product.id)
    .slice(0, limit);
};

export const searchProducts = (query: string) => {
  const lowercaseQuery = query.toLowerCase();
  return products.filter(
    (product) =>
      product.name.toLowerCase().includes(lowercaseQuery) ||
      product.description.toLowerCase().includes(lowercaseQuery) ||
      product.category.toLowerCase().includes(lowercaseQuery)
  );
};

export const getPopularProducts = (limit = 8) => {
  return products.filter((product) => product.popular).slice(0, limit);
};

export const getFeaturedProducts = (limit = 8) => {
  return products.slice(0, limit);
};
